#项目配置
server:
  port: 8080
  servlet:
    context-path: /girl

spring:
#  #springMVC
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp
  #mysql数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 123456
  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #thymeleaf模板引擎
  thymeleaf:
    # 关闭缓存及时刷新
    cache: true
#    prefix: classpath:/templates
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
  #热部署
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置目录
      additional-paths: src/main/java




